# Generated by Django 3.0.3 on 2020-04-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=128)),
                ('Lastname', models.CharField(max_length=128)),
                ('Email', models.EmailField(max_length=264, unique=True)),
            ],
        ),
    ]
